// Auto-generated by rust_elm_types

#[derive(Debug, serde::Serialize, serde::Deserialize)]
pub struct FileData {
    pub filename: String,
    pub content: String,
}

#[derive(Debug, serde::Serialize, serde::Deserialize)]
#[serde(tag = "var", content = "vardata")]
pub enum LogLevel {
    Error,
    Warn,
    Info,
    Debug,
}

#[derive(Debug, serde::Serialize, serde::Deserialize)]
#[serde(tag = "var", content = "vardata")]
pub enum ToRustMsg {
    Log {
        level: LogLevel,
        msg: String,
    },
    UploadFile(FileData),
}

#[derive(Debug, serde::Serialize, serde::Deserialize)]
#[serde(tag = "var", content = "vardata")]
pub enum FromRustMsg {
    Loading,
    EditFile(FileData),
}
